# Generated by Django 3.1.7 on 2022-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
