# Generated by Django 3.1.7 on 2022-03-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0012_product_mcate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mcate',
        ),
    ]
